# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 15:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=18, verbose_name='IP address or mask')),
                ('reason_for_block', models.TextField(blank=True, help_text='Optional reason for block', null=True)),
                ('ban_length_days', models.IntegerField(default=666666666)),
                ('ban_start', models.DateTimeField(auto_now_add=True)),
                ('banned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IPs & masks to ban',
                'verbose_name_plural': 'IPs & masks to ban',
            },
        ),
    ]
